name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install --skip-integrity-check --frozen-lockfile --non-interactive --no-progress

      - name: Lint
        run: yarn run prettier --check '{src,storybook}/**/*.{js,ts,tsx}'

      - name: Type Check
        run: yarn type-check
