name: CD/Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: v2-yarn-cache-${{ runner.OS }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v2-yarn-cache-${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn install --skip-integrity-check --frozen-lockfile --non-interactive --no-progress

      - name: Publish to Expo
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn expo login --non-interactive -u "$EXPO_CLI_USERNAME"
          yarn run publish
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
